---
title: "map2.0"
author: "AMH"
date: "10/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/hrusk/OneDrive/Documents/Land_Sea_linkages/GlobalHotspots")
setwd("~/Land_Sea_linkages/GlobalHotspots")
getwd()
```

Load libraries and import data
```{r}

library(tidyverse)
library(devtools)
library(maps)
library(maptools)
library(scatterpie)
library(ggmap)
library(reshape2)
library(gridExtra)
library(ggpubr)


htspts <- read.csv("GlobalHotspots_allterms_18May2022.csv")

```


Clean/prepare data
```{r}

htspts <- htspts %>%
  mutate(imp.factor =
           case_when (Source.Title == "ECOLOGICAL MONOGRAPHS" ~ 10.315,
                      Source.Title == "ECOLOGY LETTERS" ~ 9.492,
                      Source.Title == "PROCEEDINGS OF THE ROYAL SOCIETY B-BIOLOGICAL SCIENCES" ~ 5.349, 
                      Source.Title == "AQUATIC MICROBIAL ECOLOGY" ~ 2.024,
                      Source.Title == "HYDROBIOLOGIA" ~ 2.385,
                      Source.Title == "CONSERVATION BIOLOGY" ~ 5.405,
                      Source.Title == "PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES OF AMERICA" ~ 11.2, 
                      Source.Title == "LIMNOLOGY AND OCEANOGRAPHY" ~ 4.745, 
                      Source.Title == "DEEP-SEA RESEARCH PART I-OCEANOGRAPHIC RESEARCH PAPERS" ~ 2.955, 
                      Source.Title == "RIVER RESEARCH AND APPLICATIONS" ~ 2.443,
                      Source.Title == "OIKOS" ~ 3.71, 
                      Source.Title == "ECOLOGY" ~ 5.175,
                      Source.Title == "GLOBAL CHANGE BIOLOGY" ~ 10.86,
                      Source.Title == "JOURNAL OF ANIMAL ECOLOGY" ~ 5.09,
                      Source.Title == "AMBIO" ~ 5.129,
                      Source.Title == "BIOSCIENCE" ~ 8.59, 
                      Source.Title == "OECOLOGIA" ~ 3.011, 
                      Source.Title == "ECOSCIENCE" ~ 1.95,
                      Source.Title == "ECOHYDROLOGY" ~ 2.834, 
                      Source.Title == "FRONTIERS IN ENVIRONMENTAL SCIENCE" ~ 4.24, 
                      Source.Title == "ECOLOGICAL APPLICATIONS" ~ 4.657,
                      Source.Title == "SCIENCE ADVANCES" ~ 14.14, 
                      Source.Title == "BULLETIN OF MARINE SCIENCE" ~ 1.632,
                      Source.Title == "ECOSYSTEMS" ~ 4.217,
                      Source.Title == "SCIENCE OF THE TOTAL ENVIRONMENT" ~ 7.963,
                      Source.Title == "JOURNAL OF INTEGRATIVE PLANT BIOLOGY" ~ 7.061,
                      Source.Title == "NATURE COMMUNICATIONS" ~ 14.92,
                      Source.Title == "EUROPEAN JOURNAL OF SOIL SCIENCE" ~ 4.29, 
                      Source.Title == "EARTH-SCIENCE REVIEWS" ~ 12.41,
                      Source.Title == "MARINE ECOLOGY PROGRESS SERIES" ~ 2.359,
                      Source.Title == "ESTUARIES AND COASTS" ~ 2.319,
                      Source.Title == "BIOGEOCHEMISTRY" ~ 4.50, 
                      Source.Title == "PROGRESS IN OCEANOGRAPHY" ~ 4.08,
                      Source.Title == "FISHERIES RESEARCH" ~ 1.903,
                      Source.Title == "HYDROLOGY AND EARTH SYSTEM SCIENCES" ~ 5.748,
                      Source.Title == "FRESHWATER BIOLOGY" ~ 3.809,
                      Source.Title == "ECOLOGICAL ENTOMOLOGY" ~ 2.465, 
                      Source.Title == "IBIS" ~ 1.804,
                      Source.Title == "COPEIA" ~ 1.22, 
                      Source.Title == "ECOLOGICAL MODELLING" ~ 2.363, 
                      Source.Title == "ECOLOGY AND EVOLUTION" ~ 2.91,
                      Source.Title == "AQUATIC SCIENCES" ~ 0.778, 
                      Source.Title == "GLOBAL ECOLOGY AND BIOGEOGRAPHY" ~ 5.667, 
                      Source.Title == "FRONTIERS IN MARINE SCIENCE" ~ 4.435, 
                      Source.Title == "JOURNAL OF APPLIED ECOLOGY" ~ 6.53, 
                      Source.Title == "FRONTIERS IN ECOLOGY AND EVOLUTION" ~ 4.171, 
                      Source.Title == "BEHAVIORAL ECOLOGY" ~ 2.671, 
                      Source.Title == "LIMNOLOGY AND OCEANOGRAPHY LETTERS" ~ 7.875,
                      Source.Title == "BMC ECOLOGY" ~ 3.26, 
                      Source.Title == "ECOSPHERE" ~ 3.171, 
                      Source.Title == "SCIENCE" ~ 47.728, 
                      Source.Title == "EARTH AND PLANETARY SCIENCE LETTERS" ~ 5.255, 
                      Source.Title == "MOLECULAR ECOLOGY" ~ 6.185, 
                      Source.Title == "MARINE GEOLOGY" ~ 2.71, 
                      Source.Title == "JOURNAL OF GEOPHYSICAL RESEARCH-ATMOSPHERES" ~ 4.261, 
                      Source.Title == "JOURNAL OF CLIMATE" ~ 5.148, 
                      Source.Title == "PALAEOGEOGRAPHY PALAEOCLIMATOLOGY PALAEOECOLOGY" ~ 3.318, 
                      Source.Title == "INTERNATIONAL GEOLOGY REVIEW" ~ 3.43, 
                      Source.Title == "CLIMATE DYNAMICS" ~ 4.375, 
                      Source.Title == "CLIMATIC CHANGE" ~4.743, 
                      Source.Title == "GEOLOGICA CARPATHICA" ~ 1.699, 
                      Source.Title == "JOURNAL OF BIOGEOGRAPHY" ~ 3.72, 
                      Source.Title == "RENEWABLE & SUSTAINABLE ENERGY REVIEWS" ~ 14.98, 
                      Source.Title == "JOURNAL OF GEODYNAMICS" ~ 2.345, 
                      Source.Title == "GEOBIOS" ~ 1.243, 
                      Source.Title == "BIOGEOSCIENCES" ~ 4.295, 
                      Source.Title == "EVOLUTION" ~ 3.742, 
                      Source.Title == "JOURNAL OF ADVANCES IN MODELING EARTH SYSTEMS" ~ 6.68, 
                      Source.Title == "ANNUAL REVIEW OF ECOLOGY, EVOLUTION, AND SYSTEMATICS, VOL 42" ~ 13.915, 
                      Source.Title == "TELLUS SERIES B-CHEMICAL AND PHYSICAL METEOROLOGY" ~ 2.279, 
                      Source.Title == "CHINESE SCIENCE BULLETIN" ~ 11.78, 
                      Source.Title == "JOURNAL OF GEOPHYSICAL RESEARCH-PLANETS" ~ 4.267, 
                      Source.Title == "TERRA NOVA" ~ 2.86, 
                      Source.Title == "PHILOSOPHICAL TRANSACTIONS OF THE ROYAL SOCIETY A-MATHEMATICAL PHYSICAL AND ENGINEERING SCIENCES" ~ 4.226, 
                      Source.Title == "JOURNAL OF THE ATMOSPHERIC SCIENCES" ~ 3.184, 
                      Source.Title == "SOCIAL SCIENCE & MEDICINE" ~ 4.634, 
                      Source.Title == "GLOBAL BIOGEOCHEMICAL CYCLES" ~ 5.703, 
                      Source.Title == "EARTH SURFACE PROCESSES AND LANDFORMS" ~ 4.133, 
                      Source.Title == "NATURE" ~ 49.96, 
                      Source.Title == "BMC EVOLUTIONARY BIOLOGY" ~ 3.26, 
                      Source.Title == "IEEE JOURNAL OF SELECTED TOPICS IN APPLIED EARTH OBSERVATIONS AND REMOTE SENSING" ~ 3.827, 
                      Source.Title == "SEDIMENTARY GEOLOGY" ~  2.665, 
                      Source.Title == "JOURNAL OF PLANKTON RESEARCH" ~ 2.209, 
                      Source.Title == "QUATERNARY SCIENCE REVIEWS" ~ 4.571, 
                      Source.Title == "MOLECULAR PHYLOGENETICS AND EVOLUTION" ~ 4.286, 
                      Source.Title == "APPLIED ENERGY" ~ 9.746, 
                      Source.Title == "SYSTEMATIC BIOLOGY" ~ 15.68, 
                      Source.Title == "MAMMAL REVIEW" ~ 4.927, 
                      Source.Title == "GEOLOGICAL SOCIETY OF AMERICA BULLETIN" ~ 4.212, 
                      Source.Title == "INTERNATIONAL JOURNAL OF CLIMATOLOGY" ~ 4.069, 
                      Source.Title == "JOURNAL OF HYDROLOGY" ~ 5.722, 
                      Source.Title == "GEOCHIMICA ET COSMOCHIMICA ACTA" ~ 5.01, 
                      Source.Title == "JOURNAL OF EXPERIMENTAL MARINE BIOLOGY AND ECOLOGY" ~ 1.796, 
                      Source.Title == "GEOPHYSICAL RESEARCH LETTERS" ~ 4.72, 
                      Source.Title == "BIOLOGICAL CONSERVATION" ~ 5.99, 
                      Source.Title == "ENERGY" ~ 7.147, 
                      Source.Title == "JOURNAL OF GEOPHYSICAL RESEARCH-OCEANS" ~ 3.405, 
                      Source.Title == "ENVIRONMENTAL EARTH SCIENCES" ~ 2.18, 
                      Source.Title == "JOURNAL OF COASTAL RESEARCH" ~ 0.915, 
                      Source.Title == "ADVANCES IN ATMOSPHERIC SCIENCES" ~ 3.158, 
                      Source.Title == "GEOLOGY" ~ 5.399, 
                      Source.Title == "MARINE GEOLOGY" ~ 2.71, 
                      Source.Title == "AAPG BULLETIN" ~ 1.964, 
                      Source.Title == "ESTUARINE COASTAL AND SHELF SCIENCE" ~ 2.929, 
                      Source.Title == "CLIMATE RESEARCH" ~ 1.972, 
                      Source.Title == "ENVIRONMENTAL CONSERVATION" ~ 2.62, 
                      Source.Title == "COASTAL MANAGEMENT" ~ 1.43, 
                      Source.Title == "MARINE POLLUTION BULLETIN" ~ 5.553, 
                      Source.Title == "JOURNAL OF THE NORTH AMERICAN BENTHOLOGICAL SOCIETY" ~ 2.706, 
                      Source.Title == "CHINESE JOURNAL OF OCEANOLOGY AND LIMNOLOGY" ~ 1.265, 
                      Source.Title == "JOURNAL OF COASTAL CONSERVATION" ~ 1.861, 
                      Source.Title == "PLOS ONE" ~ 3.24, 
                      Source.Title == "ENVIRONMENTAL MANAGEMENT" ~ 3.20, 
                      Source.Title == "AQUATIC CONSERVATION-MARINE AND FRESHWATER ECOSYSTEMS" ~ 2.935, 
                      Source.Title == "CORAL REEFS" ~ 3.60, 
                      Source.Title == "SUSTAINABILITY" ~ 3.251, 
                      Source.Title == "REMOTE SENSING" ~ 4.509, 
                      Source.Title == "JOURNAL OF ENVIRONMENTAL SCIENCE AND MANAGEMENT" ~ 0.27, 
                      Source.Title == "ENVIRONMENTAL RESEARCH LETTERS" ~ 6.793, 
                      Source.Title == "JOURNAL FOR NATURE CONSERVATION" ~ 2.831, 
                      Source.Title == "HYDROLOGICAL SCIENCES JOURNAL-JOURNAL DES SCIENCES HYDROLOGIQUES" ~ 3.787, 
                      Source.Title == "FOREST ECOLOGY AND MANAGEMENT" ~ 3.126, 
                      Source.Title == "RESTORATION ECOLOGY" ~ 2.721, 
                      Source.Title == "ACS EARTH AND SPACE CHEMISTRY" ~ 3.475, 
                      Source.Title == "FRONTIERS IN ECOLOGY AND THE ENVIRONMENT" ~ 11.12, 
                      Source.Title == "CONSERVATION LETTERS" ~ 8.105
                      ))
                      


##remove excess citation information##
htspts2 <- htspts %>%
  select(Search_Term, Title, Publication.Year, Location, Linkage, Terrestiral, Freshwater, Marine, Biotic_Abiotic, flows, global_change_y.n, Global_Change, observational, empirical, modelling, review, imp.factor)

htspts2[htspts2 == "Euope"] <- "Europe"
htspts2[htspts2 == "Atlantic"] <- "North America"
htspts2[htspts2 == "Indonesia"] <- "Asia"
htspts2[htspts2 == "Antarctica"] <- "Antarctic"
htspts2[htspts2 == "China"] <- "Asia"
htspts2[htspts2 == "Russia"] <- "Asia"
htspts2[htspts2 == "South Asia"] <- "Asia"
htspts2[htspts2 == "East Asia"] <- "Asia"
htspts2[htspts2 == "Slovenia"] <- "Europe"
htspts2[htspts2 == "North Africa"] <- "Africa"
htspts2[htspts2 == "South Africa"] <- "Africa"
htspts2[htspts2 == "Aegean Sea"] <- "Europe"
htspts2[htspts2 == "Australia"] <- "Australia"
htspts2[htspts2 == "Arctic"] <- "North America"

##add long, lat columns##
htspts2 <- htspts2 %>%
  mutate(long = 
           case_when(Location == "North America" ~ "-105.292874",
                     Location == "Europe" ~ "14.894560", 
                     Location == "South America" ~ "-58.688401",
                     Location == "Europe" ~ "17.519120", 
                     Location == "Asia" ~ "103.556080", 
                     Location == "Indo-Pacific" ~ "148.701914", 
                     Location == "Africa" ~ "23.020810", 
                     Location == "Arctic" ~ "14.894560", 
                     Location == "Antarctic" ~ "-10.298374", 
                     Location == "Global" ~ "14.684516"
                     ))
         
htspts2 <- htspts2 %>%
  mutate(lat = 
           case_when(Location == "North America" ~ "48.729626",
                     Location == "Europe" ~ "48.458352", 
                     Location == "South America" ~ "-16.355278",
                     Location == "Europe" ~ "48.380558", 
                     Location == "Asia" ~ "55.842422", 
                     Location == "Indo-Pacific" ~ "3.981107", 
                     Location == "Africa" ~ "9.102097", 
                     Location == "Arctic" ~ "48.380558", 
                     Location == "Antarctic" ~ "-73.158953", 
                     Location == "Global" ~ "105.006303"
                     ))
         
         
## remove non-target data studies ##
htspts3 <- htspts2 %>%
  filter(Linkage == "direct")

## create data for linkages pie charts ##

link <- htspts2 %>%
  group_by(Location, lat, long) %>%
  count(Linkage) %>%
  filter(Linkage == "direct"| Linkage == "indirect")


link1 <- na.omit(link)

link2 <- dcast(link1, Location + lat + long ~ Linkage)
link2[is.na(link2)] <- 0
link2$lat <- as.numeric(link2$lat)
link2$long <- as.numeric(link2$long)
link2$total <- link2$direct + link2$indirect

link2 <- link2 %>%
  mutate(radius = case_when(between(total, 0, 14) ~ 6, 
                            between(total, 15, 28) ~ 12,
                            between(total, 29, 42) ~ 18))

link2 <- link2 %>%
  mutate(groups = case_when(between(total, 0, 14) ~ "<14", 
                            between(total, 15, 28) ~ "15-28",
                            between(total, 29, 42) ~ ">29"))


## create data for biotic, abiotic, both pie charts ##

ba <- htspts3 %>%
  group_by(Location, lat, long) %>%
  count(Biotic_Abiotic) %>%
  ungroup()

ba2 <- dcast(ba, Location + lat + long ~ Biotic_Abiotic)
ba2[is.na(ba2)] <- 0
ba2$lat <- as.numeric(ba2$lat)
ba2$long <- as.numeric(ba2$long)
ba2$total <- ba2$biotic + ba2$abiotic + ba2$both

ba2 <- ba2 %>%
  mutate(radius = case_when(between(total, 0, 14) ~ 6, 
                            between(total, 15, 28) ~ 12,
                            between(total, 29, 42) ~ 18))

ba2 <- ba2 %>%
  mutate(groups = case_when(between(total, 0, 14) ~ "<14", 
                            between(total, 15, 28) ~ "15-28",
                            between(total, 29, 42) ~ ">29"))

ba2$lat <- as.character(ba2$lat)
ba2$long <- as.character(ba2$long)

ba3 <- ba2 %>% 
  add_row(Location = "Global Trends", lat = "120.00000", long = "15", abiotic = 38, biotic = 38, both = 16, total = 92, radius = 22, groups = ">29", )

ba3$lat <- as.double(ba3$lat)
ba3$long <- as.double(ba3$long)

## manipulate data for terrestrial, freshwater, marine ##

ecosystem <- htspts3 %>%
  group_by(Location, lat, long) %>%
  count(Terrestiral, Freshwater, Marine) %>%
  unite("connection", Terrestiral:Marine, sep = "-") %>%
  ungroup()

ecosystem[ecosystem == "y-y-y"] <- "all"
ecosystem[ecosystem == "n-y-y"] <- "fre_mar"
ecosystem[ecosystem == "y-y-n"] <- "ter_fre"
ecosystem[ecosystem == "y-n-y"] <- "ter_mar"
ecosystem[ecosystem == "n-y-y"] <- "fre_mar"

eco2 <- dcast(ecosystem, Location + lat + long ~ connection)
eco2[is.na(eco2)] <- 0
eco2$lat <- as.numeric(eco2$lat)
eco2$long <- as.numeric(eco2$long)
eco2$total <- eco2$all + eco2$fre_mar + eco2$ter_fre + eco2$ter_mar + eco2$fre_mar

eco2 <- eco2 %>%
  mutate(radius = case_when(between(total, 0, 14) ~ 6, 
                            between(total, 15, 28) ~ 12,
                            between(total, 29, 42) ~ 18))

eco2 <- eco2 %>%
  mutate(groups = case_when(between(total, 0, 14) ~ "<14", 
                            between(total, 15, 28) ~ "15-28",
                            between(total, 29, 42) ~ ">29"))

eco2$lat <- as.character (eco2$lat)
eco2$long <- as.character(eco2$long)

eco3 <- eco2 %>%
  add_row(Location = "Global Trends", lat = "108.00000", long = "15", all = 33, fre_mar = 9, ter_fre = 38, ter_mar = 12, total = 92, radius = 22, groups = ">29", )


eco3$lat <- as.double(eco3$lat)
eco3$long <- as.double(eco3$long)


## search terms ##
term <- htspts3 %>%
  group_by(Location, lat, long) %>%
  count(Search_Term) %>%
  ungroup()

term2 <- dcast(term, Location + lat + long ~ Search_Term)
term2[is.na(term2)] <- 0
term2$lat <- as.numeric(term2$lat)
term2$long <- as.numeric(term2$long)
term2$total <- term2$`cross-ecosystem` + term2$land_to_sea_connections + term2$`ridge-to-reef`

term2 <- term2 %>%
  mutate(radius = case_when(between(total, 0, 14) ~ 6, 
                            between(total, 15, 28) ~ 12,
                            between(total, 29, 42) ~ 18))

```

Create world map 
```{r}

mapWorld <- borders("world", colour="gray50", fill="gray50") # create a layer of borders
mp <- ggplot() +   mapWorld

world <- map_data('world')
mp2 <- ggplot(world, aes(long, lat)) +
  geom_map(map = world, aes(map_id = region), fill = "gray", color = "white") +
  coord_quickmap()


```

world map with Flow Pies charted on top
```{r}
setwd("C:/Users/hrusk/OneDrive/Documents/Land_Sea_linkages/GlobalHotspots")

ba4 <- ba3 %>%
  filter(Location != "Global Trends")

#####global trends pichart#####

#create data frame#
Trends1 <- data.frame(
          group = c("abiotic", "biotic", "both"), 
          value = c(.413, .413, .174))
          

#create pie chart#
flows1 <- ggplot(Trends1, aes(x="", y=value, fill=group)) +
  geom_bar(stat="identity", width=1, color = "black") +
  geom_text(aes(label = c(38, 38, 16)), position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") +
  scale_fill_manual(values = c("#d01c8b", "#4dac26", "#f7f7f7"), name = "Flows", labels = c("Abiotic", "Biotic", "Both")) +
  theme(panel.background = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y = element_blank(), legend.position = "none")+
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5))
 
#map of continent trends#
world <- map_data('world')
mp2 <- ggplot(world, aes(long, lat)) +
  geom_map(map = world, aes(map_id = region), fill = "gray", color = "white") +
  coord_quickmap()

flows2 <- mp2 + geom_scatterpie(aes(x = long, y = lat, r=radius), data = ba4, cols = c("abiotic", "biotic", "both")) +
  annotate("text", x= -103, y = 74, size = 3.5, label = "North America", fontface = "bold") +
  annotate("text", x= 15.5, y = 63, size = 3.5, label = "Europe", fontface = "bold") +
  annotate("text", x= -58, y = -5, size = 3.5, label = "South America", fontface = "bold") +
  annotate("text", x= 105, y = 68, size = 3.5, label = "Asia", fontface = "bold") +
  annotate("text", x= 152, y = 23, size = 3.5, label = "Indo-Pacific", fontface = "bold") +
  annotate("text", x= 20, y = 23, size = 3.5, label = "Africa", fontface = "bold") +
  annotate("text", x= -10, y = -60, size = 3.5, label = "Antarctica", fontface = "bold") +
  annotate("text", x= 15, y = 125, size = 3.5, label = "Global", fontface = "bold") +
  annotate("text", x = -140, y = -18, size = 3.5, label = "Number of Articles") +
  scale_fill_manual(values = c("#d01c8b", "#4dac26", "#f7f7f7"), name = "Flows", labels = c("Abiotic", "Biotic", "Both")) +
  theme(panel.background = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y = element_blank(), legend.position = "none", legend.box = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  geom_scatterpie_legend(ba3$radius, x = -160, y = -53, n = 3, labeller = function(a) a = c("<14", "15-28", ">28")) 
  

fig1 <- ggarrange(flows2, flows1, ncol = 2, labels = "A", widths = c(5,1.25), heights = c(3,2), common.legend = TRUE, legend = "bottom")

annotate_figure(fig1,
               top = text_grob("Overall Trends", face = "bold", size = 10, hjust = -2.4, vjust = 13))

setwd("~/Land_Sea_linkages/GlobalHotspots")
ggsave(file = "biotic_abiotic2.png", width = 7, height = 4.5, units = "in", dpi = 800)

#annotate("text", x = -170, y = 140, size = 4, label = "A)", fontface = "bold") +
  #annotate("text", x = 170, y = 140, size = 4, label = "B)", fontface = "bold") +

```


world map of ecosystem connections of direct linkage studies
```{r}
setwd("C:/Users/hrusk/OneDrive/Documents/Land_Sea_linkages/GlobalHotspots")

eco4 <- eco3 %>%
  filter(Location != "Global Trends")

#####global trends pichart#####

#create data frame#
Trends2 <- data.frame(
          group = c("ter_fre", "fre_mar", "ter_mar", "all"), 
          value = c(38, 9, 12, 33))
          

#create pie chart#
ecos1 <- ggplot(Trends2, aes(x="", y=value, fill=group)) +
  geom_bar(stat="identity", width=1, color = "black") +
  geom_text(aes(label = value), position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y") +
  scale_fill_manual(values = c("#225ea8", "#41b6c4", "#a1dab4", "#ffffcc"), name = "Connections", labels = c("Terrestrial-Freshwater", "Freshwater-Marine", "Terrestrial-Marine", "All")) +
  theme(panel.background = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y = element_blank(), legend.position = "none")
  
 


world <- map_data('world')
mp3 <- ggplot(world, aes(long, lat)) +
  geom_map(map = world, aes(map_id = region), fill = "gray", color = "white") +
  coord_quickmap()

ecos2 <- mp3 + geom_scatterpie(aes(x = long, y = lat, r = radius), data = eco4, cols = c("ter_fre", "fre_mar", "ter_mar", "all")) +
  annotate("text", x= -105, y = 73, size = 3.5, label = "North America", fontface = "bold") +
  annotate("text", x= 15.5, y = 68, size = 3.5, label = "Europe", fontface = "bold") +
  annotate("text", x= -57, y = -2, size = 3.5, label = "South America", fontface = "bold") +
  annotate("text", x= 104, y = 69, size = 3.5, label = "Asia", fontface = "bold") +
  annotate("text", x= 153, y = 23, size = 3.5, label = "Indo-Pacific", fontface = "bold") +
  annotate("text", x= 23, y = 22, size = 3.5, label = "Africa", fontface = "bold") +
  annotate("text", x= -10, y = -60, size = 3.5, label = "Antarctica", fontface = "bold") +
  annotate("text", x= 15, y = 125, size = 3.5, label = "Global", fontface = "bold") +
  annotate("text", x = -140, y = -15, size = 3.5, label = "Number of Articles") +
  scale_fill_manual(values = c("#225ea8", "#41b6c4", "#a1dab4", "#ffffcc"), name = "Connections", labels = c("Terrestrial-Freshwater", "Freshwater-Marine", "Terrestrial-Marine", "All")) +
  theme(panel.background = element_blank(), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.title.y = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y = element_blank(), legend.position = "none", legend.box = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  geom_scatterpie_legend(eco3$radius, x = -150, y = -50, n = 3, labeller = function(a) a = c("<14", "15-28", ">28"))
  
  
 
fig2 <- ggarrange(ecos2, ecos1, ncol = 2, labels = "B", widths = c(5,1.25), heights = c(3,2), common.legend = TRUE, legend = "bottom")

annotate_figure(fig2,
               top = text_grob("Overall Trends", face = "bold", size = 10, hjust = -2.4, vjust = 13))



ggsave(file = "ecosystem_connection2.png", width = 7, height = 4.5, unit = "in", dpi = 700)
```


```{r}

ggarrange(flows2, flows1, ncol = 2, labels = "A", widths = c(5,1.5), heights = c(3,2), common.legend = TRUE, legend = "bottom")

ggarrange(ecos2, ecos1, ncol = 2, labels = "B", widths = c(5,1), heights = c(3,2), common.legend = TRUE, legend = "bottom")


```



world map of direct and indirect linkages
```{r}
mp2 + geom_scatterpie(aes(x = long, y = lat, r=radius), data = link2, cols = c("direct", "indirect")) +
    theme(legend.position = "bottom") +
  annotate("text", x= -105, y = 73, size = 3, label = "North America", fontface = "bold") +
  annotate("text", x= 15.5, y = 66, size = 3, label = "Europe", fontface = "bold") +
  annotate("text", x= -57, y = -5, size = 3, label = "South America", fontface = "bold") +
  annotate("text", x= 104, y = 67, size = 3, label = "Asia", fontface = "bold") +
  annotate("text", x= 153, y = 21, size = 3, label = "Indo-Pacific", fontface = "bold") +
  annotate("text", x= 23, y = 20, size = 3, label = "Africa", fontface = "bold") +
  annotate("text", x= -10, y = -62, size = 3, label = "Antarctica", fontface = "bold") +
  annotate("text", x= 161, y = 124, size = 3, label = "Global", fontface = "bold") +
  annotate("text", x = -130, y = -20, size = 3.5, label = "Number of Articles") +
    scale_fill_manual(values = c("#2c7fb8", "#edf8b1"),name = "Linkage", labels = c("Direct", "Indirect")) +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
 geom_scatterpie_legend(link2$radius, x = -140, y = -50, n = 3, labeller = function(a) a = c("<14", "15-28", ">28"))

ggsave(file = "linkages.png", dpi = 700)

```




world map of search terms with direct linkages
```{r}
mp2 + geom_scatterpie(aes(x = long, y = lat, r=radius), data = term2, cols = c("cross-ecosystem", "land_to_sea_connections", "ridge-to-reef")) +
  annotate("text", x= -105, y = 73, size = 3, label = "North America", fontface = "bold") +
  annotate("text", x= 15.5, y = 60, size = 3, label = "Europe", fontface = "bold") +
  annotate("text", x= -57, y = -5, size = 3, label = "South America", fontface = "bold") +
  annotate("text", x= 104, y = 67, size = 3, label = "Asia", fontface = "bold") +
  annotate("text", x= 153, y = 21, size = 3, label = "Indo-Pacific", fontface = "bold") +
  annotate("text", x= 23, y = 20, size = 3, label = "Africa", fontface = "bold") +
  annotate("text", x= -10, y = -62, size = 3, label = "Antarctica", fontface = "bold") +
  annotate("text", x= 161, y = 118, size = 3, label = "Global", fontface = "bold") +
  annotate("text", x = -130, y = -20, size = 3.5, label = "Number of Articles") +
  theme(legend.position = "bottom", legend.box = "horizontal") +
  guides(fill = guide_legend(title.position = "top", title.hjust = 0.5)) +
  scale_fill_manual(values = c("#2c7fb8", "#7fcdbb", "#edf8b1"), name = "Search Term", labels = c("cross ecosystem", "land to sea connections", "ridge-to-reef")) +
  geom_scatterpie_legend(term2$radius, x = -140, y = -50, n = 3, labeller = function(a) a = c("<14", "15-28", ">28"))+
   annotate("rect", xmin=142, xmax = 180, ymin = 94, ymax = 158, alpha = 0.2, color = "black", fill = NA)

ggsave("search_terms.png", dpi = 700)
```


